version: '3.8'

services:
  mysql-reservas:
    image: mysql:8.0
    container_name: mysql-reservas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitlife_reservas_db
    ports:
      - "3307:3306"
    networks:
      - fitlife-network
    volumes:
      - mysql-reservas-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-reservas:
    build: .
    container_name: ms-reservas
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-reservas:3306/fitlife_reservas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - fitlife-network
    depends_on:
      mysql-reservas:
        condition: service_healthy
    restart: always

networks:
  fitlife-network:
    driver: bridge

volumes:
  mysql-reservas-data:
